# Generated by Django 5.2.12 on 2026-04-08 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0005_lotecerdos_costo_inicial'),
        ('inventario', '0002_proveedor_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad consumida (Sacos/Kilos)')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Costo de este consumo para finanzas', max_digits=12)),
                ('alimento', models.ForeignKey(limit_choices_to={'categoria': 'ALIMENTO'}, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='granja.lotecerdos')),
            ],
        ),
    ]
