# Generated by Django 5.2.12 on 2026-04-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAPAYA', 'Papaya'), ('PLATANO', 'Plátano')], max_length=10)),
                ('area_manzanas', models.FloatField()),
                ('fecha_siembra', models.DateField()),
                ('estado', models.CharField(choices=[('CRECIMIENTO', 'En Crecimiento'), ('COSECHA', 'En Cosecha'), ('FINALIZADO', 'Finalizado')], default='CRECIMIENTO', max_length=15)),
                ('cantidad_estimada', models.IntegerField(help_text='Unidades estimadas')),
            ],
        ),
        migrations.CreateModel(
            name='LoteCerdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_batch', models.CharField(max_length=50, unique=True, verbose_name='ID de Lote')),
                ('fecha_entrada', models.DateField()),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_actual', models.IntegerField()),
                ('peso_promedio_inicial', models.FloatField(help_text='Peso en kg')),
                ('raza', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ENGORDE', 'Engorde'), ('CRIA', 'Cría'), ('DESTETE', 'Destete')], default='ENGORDE', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(help_text='Ej: Vacuna contra parvovirus', max_length=200)),
                ('tratamiento', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
    ]
