# Generated by Django 5.2.12 on 2026-04-07 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0002_cultivo_lotecerdos_registrosalud'),
        ('ventas', '0002_carrito_remove_venta_animales_remove_venta_productos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.AddField(
            model_name='registrosalud',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_salud', to='granja.lotecerdos'),
        ),
    ]
