# Generated by Django 5.2.12 on 2026-04-08 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0003_delete_animal_registrosalud_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecerdos',
            name='peso_actual',
            field=models.FloatField(default=0, help_text='Peso promedio actual en kg'),
        ),
        migrations.AlterField(
            model_name='lotecerdos',
            name='peso_promedio_inicial',
            field=models.FloatField(help_text='Peso en kg al entrar'),
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.FloatField(help_text='Peso registrado en esta fecha')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pesos', to='granja.lotecerdos')),
            ],
        ),
    ]
