# Generated by Django 5.2.12 on 2026-04-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0004_lotecerdos_peso_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecerdos',
            name='costo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='C$ invertidos inicialmente', max_digits=12),
        ),
    ]
