# Generated by Django 5.2.12 on 2026-04-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0005_lotecerdos_costo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecerdos',
            name='estado',
            field=models.CharField(choices=[('SALUDABLE', 'Saludable'), ('OBSERVACION', 'Observación'), ('REVISION', 'Revisión'), ('ENGORDE', 'Engorde'), ('CRIA', 'Cría'), ('DESTETE', 'Destete')], default='SALUDABLE', max_length=20),
        ),
    ]
