# Generated by Django 5.2.12 on 2026-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0006_alter_lotecerdos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecerdos',
            name='edad_inicial_semanas',
            field=models.IntegerField(default=0, help_text='Semanas de vida al entrar al lote'),
        ),
    ]
