# Generated by Django 5.2.12 on 2026-04-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0007_lotecerdos_edad_inicial_semanas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecerdos',
            name='ubicacion',
            field=models.CharField(default='Corral A-1', max_length=100, verbose_name='Ubicación/Corral'),
        ),
    ]
